"""Generate or verify the repository's deterministic, non-vendor file inventory.

The script lists project-managed implementation and documentation files in a
reviewable Markdown document. It deliberately excludes dependency, build,
virtual-environment, and vendor trees so the inventory remains useful rather
than mirroring generated state.
"""

from __future__ import annotations

import argparse
import subprocess
from collections.abc import Iterable
from pathlib import Path

EXCLUDED_PARTS = {
    ".git",
    ".ipynb_checkpoints",
    ".venv",
    "__pycache__",
    "dist",
    "node_modules",
    "playwright-report",
    "test-results",
    "vendor",
}
OUTPUT_PATH = Path("docs/repository-inventory.md")


def repository_root() -> Path:
    """Return the monorepo root based on this script's fixed location.

    Returns:
        The directory containing the project's `scripts` and `docs` folders.

    Raises:
        RuntimeError: If the expected root structure has been moved or removed.
    """

    root = Path(__file__).resolve().parents[1]
    if not (root / "docs").is_dir() or not (root / "scripts").is_dir():
        raise RuntimeError(
            "Could not locate the Fraud Compliance Agent repository root."
        )
    return root


def in_scope_files(root: Path) -> Iterable[Path]:
    """Yield Git-visible project files for the deterministic inventory.

    Args:
        root: Validated monorepo root containing the Git working tree.

    Yields:
        Sorted relative paths for tracked files and non-ignored candidate files.

    Raises:
        RuntimeError: If Git cannot enumerate the repository files.

    Side effects:
        Runs a read-only Git command. It does not modify the index or worktree.
    """

    # Git's ignore engine is the repository authority for generated and local
    # files. Including untracked, non-ignored paths also makes the check useful
    # before the repository's initial commit.
    result = subprocess.run(
        [
            "git",
            "ls-files",
            "--cached",
            "--others",
            "--exclude-standard",
            "-z",
        ],
        cwd=root,
        check=False,
        capture_output=True,
    )
    if result.returncode != 0:
        message = result.stderr.decode("utf-8", errors="replace").strip()
        raise RuntimeError(f"Could not enumerate repository files: {message}")

    candidates = (
        Path(raw_path.decode("utf-8"))
        for raw_path in result.stdout.split(b"\0")
        if raw_path
    )
    # Pinned vendor contents are represented by the submodule path rather than
    # mirrored file-by-file in this project-owned inventory.
    relative_paths = {
        path
        for path in candidates
        if path != OUTPUT_PATH and not EXCLUDED_PARTS.intersection(path.parts)
    }
    yield from sorted(relative_paths, key=lambda path: path.as_posix())


def inventory_markdown(root: Path) -> str:
    """Build the exact Markdown content for the repository inventory.

    Args:
        root: Validated monorepo root whose in-scope files will be listed.

    Returns:
        Deterministic Markdown safe to commit and compare in CI.
    """

    files = list(in_scope_files(root))
    lines = [
        "# Generated repository inventory",
        "",
        "<!-- Generated by scripts/generate_repository_inventory.py; do not edit manually. -->",
        "",
        "This is the machine-maintained companion to [repository-map.md](repository-map.md).",
        "It lists project-owned files in scope and deliberately excludes dependencies, build",
        "output, virtual environments, Git metadata, notebook checkpoints, and vendor trees.",
        "Regenerate with `make repository-inventory`; verify with",
        "`make repository-inventory-check`.",
        "",
        f"**Files listed:** {len(files)}",
        "",
    ]

    current_group = ""
    for path in files:
        group = path.parts[0] if len(path.parts) > 1 else "root"
        if group != current_group:
            current_group = group
            lines.extend((f"## `{group}`", ""))
        lines.append(f"- `{path.as_posix()}`")

    return "\n".join(lines) + "\n"


def main() -> int:
    """Write the inventory or return a failing status when it is stale.

    Returns:
        Zero after a successful write or current-inventory check; one when
        `--check` detects a stale/missing committed inventory.

    Side effects:
        Writes `docs/repository-inventory.md` unless `--check` is supplied.
    """

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail instead of rewriting a stale inventory.",
    )
    args = parser.parse_args()

    root = repository_root()
    output_path = root / OUTPUT_PATH
    expected = inventory_markdown(root)
    current = output_path.read_text(encoding="utf-8") if output_path.exists() else ""

    if args.check:
        if current != expected:
            print("Repository inventory is stale. Run: make repository-inventory")
            return 1
        print("Repository inventory is current.")
        return 0

    output_path.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH} ({expected.count(chr(10))} lines).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
